name: Observer Pattern CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure

    - name: Create DEB package
      run: |
        mkdir -p observer-pkg/usr/local/bin
        cp build/observer_demo observer-pkg/usr/local/bin/
        mkdir -p observer-pkg/DEBIAN
        cat > observer-pkg/DEBIAN/control <<EOF
        Package: observer-pattern
        Version: 1.0
        Section: education
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Complete Observer Pattern Implementation
        EOF
        dpkg-deb --build observer-pkg
        mkdir artifacts
        mv observer-pkg.deb artifacts/observer-pattern_1.0_amd64.deb

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: deb-package
        path: artifacts/

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: deb-package
    - uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.deb