name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential libgtest-dev libgmock-dev
        
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        mkdir -p observer-pkg/usr/local/bin
        cp build/Behavioral/Observer/observer_demo observer-pkg/usr/local/bin/
        mkdir -p observer-pkg/DEBIAN
        cat > observer-pkg/DEBIAN/control <<EOF
        Package: observer-pattern
        Version: 1.0
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Observer Pattern Implementation
        EOF
        dpkg-deb --build observer-pkg
        mkdir artifacts
        mv observer-pkg.deb artifacts/observer-pattern_1.0_amd64.deb
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: deb-package
        path: build/artifacts/*.deb
        
  release:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: deb-package
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.deb