name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential
        
    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
        
    - name: Verify executable
      run: |
        cd build
        ./Behavioral/Observer/observer_demo