name: CI/CD with Forced Release Build
on:
  push:
    branches: [master]
  release:
    types: [created, edited]  # Триггер при создании и редактировании релиза

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build
      FORCE_REBUILD: ${{ github.event_name == 'release' }}  # Флаг принудительной пересборки

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полная история коммитов для работы с тегами

    - name: Force clean on release
      if: env.FORCE_REBUILD == 'true'
      run: |
        echo "♻️ ПРИНУДИТЕЛЬНАЯ ПЕРЕСБОРКА ДЛЯ РЕЛИЗА"
        rm -rf "$BUILD_DIR" artifacts/ pkg/
        git clean -fdx

    - name: Setup build directory
      run: |
        mkdir -p "$BUILD_DIR"
        echo "Build dir: $BUILD_DIR"
        ls -la "$BUILD_DIR/.."

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          build-essential \
          libgtest-dev \
          dpkg \
          file

    - name: Configure project
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        cmake ${{ github.workspace }} \
          -DBUILD_TESTING=OFF \
          -DVERSION_SUFFIX=-$(date +%Y%m%d-%H%M)

    - name: Build project
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        make -j$(nproc)
        file Behavioral/Observer/observer_demo  # Проверка бинарника

    - name: Create DEB package
      run: |
        mkdir -p pkg/usr/local/bin
        install -m 755 "$BUILD_DIR/Behavioral/Observer/observer_demo" pkg/usr/local/bin/
        
        mkdir -p pkg/DEBIAN
        cat <<EOF > pkg/DEBIAN/control
        Package: observer-pattern
        Version: 1.0-$(date +%Y%m%d-%H%M)
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        Description: Observer Pattern Implementation
        Depends: libc6
        EOF
        
        dpkg-deb --build pkg
        mkdir -p artifacts
        mv pkg.deb artifacts/observer-pattern.deb
        sha256sum artifacts/observer-pattern.deb > artifacts/SHA256SUMS

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-assets
        path: |
          artifacts/observer-pattern.deb
          artifacts/SHA256SUMS
        retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: release-assets
        path: release-files

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release-files/observer-pattern.deb
          release-files/SHA256SUMS
        body: |
          ### Автоматически собранный релиз
          **Дата сборки:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')  
          **Коммит:** [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})  
          **Версия пакета:** 1.0-$(date +%Y%m%d-%H%M)  

          ```bash
          # Для установки:
          wget ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/observer-pattern.deb
          sudo dpkg -i observer-pattern.deb
          ```