name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:  # Триггерим только при изменениях в коде
      - 'Behavioral/Observer/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v4

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential

    - name: Configure
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Test
      run: |
        cd build
        ctest --output-on-failure