name: CI/CD Proven
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug structure
        run: tree -L 3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ build-essential

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make

      - name: Test
        run: |
          cd build
          ./Behavioral/Observer/observer_demo
          ctest --output-on-failure || true

      - name: Prepare artifact
        run: mkdir -p artifacts && touch artifacts/dummy.deb

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: artifacts/