name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Для ручного запуска

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Ограничение времени выполнения
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          build-essential \
          libgtest-dev \
          libgmock-dev
        
    - name: Configure project
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        
    - name: Build project
      run: |
        cd build
        make -j$(nproc)
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        mkdir -p observer-pkg/usr/local/bin
        cp build/Behavioral/Observer/observer_demo observer-pkg/usr/local/bin/
        
        mkdir -p observer-pkg/DEBIAN
        cat > observer-pkg/DEBIAN/control <<EOF
        Package: observer-pattern
        Version: 1.0
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Implementation of Observer Pattern
        EOF
        
        dpkg-deb --build observer-pkg
        mkdir -p artifacts
        mv observer-pkg.deb artifacts/observer-pattern_1.0_amd64.deb
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: deb-package
        path: build/artifacts/*.deb