name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          build-essential \
          libgtest-dev

    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake -DBUILD_TESTING=ON ..
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure || (echo "Tests failed!"; exit 1)

    - name: Create DEB package
      run: |
        mkdir -p pkg/usr/local/bin
        cp build/Behavioral/Observer/observer_demo pkg/usr/local/bin/
        
        mkdir -p pkg/DEBIAN
        cat > pkg/DEBIAN/control <<EOF
        Package: observer-pattern
        Version: 1.0-$(date +%Y%m%d)
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Auto Builder <noreply@example.com>
        Description: Observer pattern implementation
        EOF
        
        dpkg-deb --build pkg
        mkdir -p artifacts
        mv pkg.deb artifacts/observer-pattern.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: deb-package
        path: build/artifacts/*.deb