name: CI/CD Pipeline with Reliable Builds
on:
  push:
    branches: [master]
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: ${{ github.workspace }}
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_DIR: ${{ github.workspace }}/pkg/usr/local/bin

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clean workspace
      run: |
        echo "Полная очистка рабочих директорий..."
        rm -rf "$BUILD_DIR" "$INSTALL_DIR" artifacts/ pkg/
        mkdir -p "$BUILD_DIR"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake=3.22* \
          g++=10.3* \
          build-essential \
          libgtest-dev=1.11* \
          dpkg \
          file

    - name: Configure project
      working-directory: $BUILD_DIR
      run: |
        echo "Конфигурация проекта..."
        echo "Исходный код: $SOURCE_DIR"
        echo "Директория сборки: $BUILD_DIR"
        cmake "$SOURCE_DIR" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DVERSION_SUFFIX=-$(date +%Y%m%d-%H%M%S)

    - name: Build project
      working-directory: $BUILD_DIR
      run: |
        echo "Сборка проекта..."
        make -j$(nproc) VERBOSE=1
        echo "Проверка бинарника:"
        file Behavioral/Observer/observer_demo
        ldd Behavioral/Observer/observer_demo || true

    - name: Create DEB package
      run: |
        echo "Создание DEB-пакета..."
        mkdir -p "$INSTALL_DIR"
        install -m 755 "$BUILD_DIR/Behavioral/Observer/observer_demo" "$INSTALL_DIR"/
        
        mkdir -p pkg/DEBIAN
        cat <<EOF > pkg/DEBIAN/control
        Package: observer-pattern
        Version: 1.0-$(date +%Y%m%d-%H%M%S)
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        Description: Observer Pattern Implementation
        Depends: libc6 (>= 2.31)
        EOF
        
        dpkg-deb --build pkg
        mkdir -p artifacts
        mv pkg.deb artifacts/observer-pattern.deb
        sha256sum artifacts/observer-pattern.deb > artifacts/SHA256SUMS
        echo "Создан пакет:"
        ls -lh artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: |
          artifacts/observer-pattern.deb
          artifacts/SHA256SUMS
        retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: debian-package
        path: release-assets

    - name: Verify package
      run: |
        echo "Проверка пакета..."
        dpkg-deb -I release-assets/observer-pattern.deb
        dpkg-deb -c release-assets/observer-pattern.deb

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release-assets/observer-pattern.deb
          release-assets/SHA256SUMS
        body: |
          ## 🚀 Собранный релиз Observer Pattern

          ### Техническая информация
          - **Версия пакета:** 1.0-$(date +%Y%m%d-%H%M%S)
          - **Коммит:** [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          - **Дата сборки:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')

          ### Установка
          ```bash
          # Скачать пакет
          wget ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/observer-pattern.deb

          # Установить с зависимостями
          sudo apt install ./observer-pattern.deb

          # Проверить контрольную сумму
          sha256sum -c SHA256SUMS
          ```

          ### Изменения
          ${{ github.event.release.body }}