name: CI/CD Pipeline (master branch)

on:
  push:
    branches: [master]  # Указываем master вместо main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
    - uses: actions/checkout@v4

    - name: Verify branch
      run: |
        echo "Текущая ветка: ${{ github.ref }}"
        [ "${{ github.ref }}" == "refs/heads/master" ] || exit 1

    - name: Clean workspace
      run: |
        rm -rf "$BUILD_DIR" || true
        mkdir -p "$BUILD_DIR"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          build-essential \
          libgtest-dev

    - name: Configure project
      working-directory: ${{ env.BUILD_DIR }}
      run: cmake ${{ github.workspace }}

    - name: Build project
      working-directory: ${{ env.BUILD_DIR }}
      run: make -j$(nproc)

    - name: Run tests
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        if [ -f "CTestTestfile.cmake" ]; then
          ctest --output-on-failure
        else
          echo "⚠️ Тесты не найдены, пропускаем"
        fi