name: Observer CI/CD
on: 
  push:
    paths:
      - 'Behavioral/Observer/**'
      - '.github/workflows/*.yml'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build_${{ github.run_id }}

    steps:
    - uses: actions/checkout@v4

    - name: Validate structure
      run: |
        [ -f CMakeLists.txt ] || { echo "CMakeLists.txt missing"; exit 1; }
        [ -d Behavioral/Observer ] || { echo "Observer dir missing"; exit 1; }
        echo "Structure OK"

    - name: Build
      run: |
        mkdir -p $BUILD_DIR
        cd $BUILD_DIR
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        ./Behavioral/Observer/observer_demo || true

    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: observer-app
        path: ${{ env.BUILD_DIR }}/Behavioral/Observer/observer_demo