name: CI/CD Pipeline for Ubuntu 24.04

on:
  push:
    branches: [master]
    tags: ['v*.*.*']  # Формат vX.Y.Z

# Права для всего workflow
permissions:
  contents: write
  packages: write
  releases: write
  id-token: write  # Критично для OIDC авторизации

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      SOURCE_DIR: ${{ github.workspace }}
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Полная история для работы с тегами

    - name: Clean workspace
      run: |
        rm -rf "$BUILD_DIR" artifacts/ pkg/
        mkdir -p "$BUILD_DIR"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          build-essential \
          libgtest-dev \
          googletest \
          dpkg-dev \
          file

    - name: Setup Google Test
      run: |
        sudo ln -s /usr/lib/googletest /usr/local/include/gtest
        sudo ln -s /usr/lib/googletest /usr/local/include/gmock

    - name: Configure project
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        cmake "$SOURCE_DIR" \
          -DCMAKE_BUILD_TYPE=Release \
          -DGTEST_ROOT=/usr/lib/googletest

    - name: Build project
      working-directory: ${{ env.BUILD_DIR }}
      run: |
        make -j$(nproc)
        file Behavioral/Observer/observer_demo

    - name: Determine package version
      id: version
      run: |
        if [[ ${{ github.ref }} == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Using tag version: $VERSION"
        else
          VERSION="0.0.0-$(date +%Y%m%d)"
          echo "Using default version: $VERSION"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create DEB package
      run: |
        mkdir -p pkg/usr/local/bin
        install -m 755 "$BUILD_DIR/Behavioral/Observer/observer_demo" pkg/usr/local/bin/
        
        mkdir -p pkg/DEBIAN
        cat <<EOF > pkg/DEBIAN/control
        Package: observer-pattern
        Version: ${{ steps.version.outputs.version }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: CI <ci@example.com>
        Description: Observer Pattern Implementation
        Depends: libc6 (>= 2.35)
        EOF
        
        dpkg-deb --build pkg
        mkdir -p artifacts
        mv pkg.deb artifacts/observer-pattern.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: artifacts/observer-pattern.deb

  create-release:
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    
    permissions:
      contents: write
      packages: write
      releases: write
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: deb-package
        path: .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ### Автоматическая сборка для Ubuntu 24.04
          **Версия:** ${{ github.ref_name }}
          **Дата сборки:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          **Коммит:** [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          
          ### Установка
          ```bash
          sudo apt install ./observer-pattern.deb
          ```
        files: |
          observer-pattern.deb
      env:
        GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}