name: CI/CD Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
    # Шаг 1: Подготовка
    - uses: actions/checkout@v4

    # Шаг 2: Очистка и создание папок
    - name: Clean workspace
      run: |
        rm -rf "$BUILD_DIR" || true
        mkdir -p "$BUILD_DIR"

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          build-essential \
          libgtest-dev \
          dpkg

    # Шаг 4: Сборка проекта
    - name: Build project
      run: |
        cd "$BUILD_DIR"
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)

    # Шаг 5: Запуск тестов
    - name: Run tests
      working-directory: $BUILD_DIR
      run: |
        ctest --output-on-failure || true

    # Шаг 6: Создание DEB-пакета
    - name: Create DEB package
      run: |
        mkdir -p pkg/usr/local/bin
        install -m 755 "$BUILD_DIR/Behavioral/Observer/observer_demo" pkg/usr/local/bin/
        
        mkdir -p pkg/DEBIAN
        cat <<EOF > pkg/DEBIAN/control
        Package: observer-pattern
        Version: 1.0-$(date +%Y%m%d)
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: CI <ci@example.com>
        Description: Observer Pattern Implementation
        Depends: libc6
        EOF
        
        dpkg-deb --build pkg
        mkdir -p artifacts
        mv pkg.deb artifacts/observer-pattern.deb

    # Шаг 7: Загрузка артефакта
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: ${{ github.workspace }}/artifacts/observer-pattern.deb
        retention-days: 3

    # Шаг 8: Публикация релиза (только при теге)
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ github.workspace }}/artifacts/observer-pattern.deb
        body: |
          Автоматическая сборка от ${{ github.event.head_commit.timestamp }}
          Хеш коммита: ${{ github.sha }}